// src/routes/(app)/payment/top-up/+page.svelte
<script lang="ts">
  import { onDestroy, onMount } from "svelte";
  import type { Attachment } from "svelte/attachments";
  import { resolve } from "$app/paths";
  import { CreateTopupCheckoutSessionStore, PaymentConfigStore } from "$houdini";
  import { loadStripe, type StripeCheckoutLoadActionsSuccess, type StripePaymentElement } from "@stripe/stripe-js";
  import { Button, FieldError, Input, PageTitle } from "$lib";
  import { PATH_PAYMENT } from "$lib/app/paths";
  import { dollarsToUsdMicros, formatUsdMicros } from "$lib/feature/payment/payment-display";
  import type { FormSubmitResult } from "text-reach-frontend-library/form";
  import { createTopUpForm, selectedTopUpAmountMicros, type SubmitValues } from "./components/form/form.svelte";

  const PRESET_AMOUNTS = [10, 25, 50, 100];

  interface PaymentConfigData {
    currency: string;
    maxTopupUsdMicros: number;
    minTopupUsdMicros: number;
    stripePublishableKey: string;
  }

  const paymentConfigQuery = new PaymentConfigStore();
  const createCheckoutSessionMutation = new CreateTopupCheckoutSessionStore();

  let paymentConfig = $state<PaymentConfigData | null>(null);
  let loadingConfig = $state(false);
  let confirming = $state(false);
  let message = $state<string | null>(null);
  let error = $state<string | null>(null);
  let paymentElementContainer = $state<HTMLDivElement | null>(null);
  let paymentElement = $state.raw<StripePaymentElement | null>(null);
  let checkoutActions = $state.raw<StripeCheckoutLoadActionsSuccess | null>(null);

  const form = createTopUpForm(startTopUp);
  const selectedAmountMicros = $derived(
    selectedTopUpAmountMicros({
      customAmount: form.customAmount.value,
      selectedPreset: form.selectedPreset.value,
    }),
  );
  const minAmountMicros = $derived(paymentConfig?.minTopupUsdMicros ?? 0);
  const maxAmountMicros = $derived(paymentConfig?.maxTopupUsdMicros ?? Number.MAX_SAFE_INTEGER);
  const amountValid = $derived(
    selectedAmountMicros >= minAmountMicros && selectedAmountMicros <= maxAmountMicros && selectedAmountMicros > 0,
  );

  onMount(() => {
    void loadPaymentConfig();
  });

  onDestroy(() => {
    paymentElement?.destroy();
  });

  async function loadPaymentConfig(): Promise<void> {
    loadingConfig = true;

    try {
      const response = await paymentConfigQuery.fetch();

      if (response.errors || !response.data) {
        handleError("Could not load payment settings.");
        return;
      }

      paymentConfig = response.data.paymentConfig;
      error = null;
    } catch {
      handleError("Could not load payment settings.");
    } finally {
      loadingConfig = false;
    }
  }

  async function startTopUp(input: SubmitValues): Promise<FormSubmitResult> {
    if (!paymentConfig || !paymentElementContainer) {
      return { error: "Could not start top up." };
    }

    if (input.amountUsdMicros < minAmountMicros || input.amountUsdMicros > maxAmountMicros) {
      return {
        error: `Enter an amount between ${formatUsdMicros(minAmountMicros)} and ${formatUsdMicros(maxAmountMicros)}.`,
      };
    }

    message = null;
    error = null;
    checkoutActions = null;
    paymentElement?.destroy();
    paymentElement = null;

    try {
      const response = await createCheckoutSessionMutation.mutate({
        input,
      });

      if (response.errors || !response.data) {
        return { error: "Could not start top up." };
      }

      const session = response.data.createTopupCheckoutSession;

      const stripe = await loadStripe(paymentConfig.stripePublishableKey);

      if (!stripe) {
        return { error: "Could not load Stripe." };
      }

      const checkout = stripe.initCheckoutElementsSdk({
        clientSecret: session.clientSecret,
        elementsOptions: {
          appearance: {
            theme: "stripe",
          },
        },
      });
      const element = checkout.createPaymentElement();
      const actionsResult = await checkout.loadActions();

      if (actionsResult.type === "error") {
        return { error: actionsResult.error.message };
      }

      element.mount(paymentElementContainer);
      paymentElement = element;
      checkoutActions = actionsResult.actions;
      message = `${formatUsdMicros(session.amountUsdMicros)} top up is ready.`;
      return {};
    } catch {
      return { error: "Could not start top up." };
    }
  }

  async function confirmPayment(): Promise<void> {
    if (!checkoutActions || confirming) {
      return;
    }

    confirming = true;
    error = null;
    message = null;

    try {
      const result = await checkoutActions.confirm({
        returnUrl: `${window.location.origin}${PATH_PAYMENT}`,
      });

      if (result.type === "error") {
        error = result.error.message;
        return;
      }

      message = "Payment submitted.";
    } catch {
      error = "Could not confirm payment.";
    } finally {
      confirming = false;
    }
  }

  function selectPreset(amount: number): void {
    form.selectedPreset.value = amount;
    form.customAmount.value = "";
  }

  const attachPaymentElementContainer: Attachment<HTMLDivElement> = (element) => {
    paymentElementContainer = element;

    return () => {
      paymentElementContainer = null;
    };
  };

  function handleError(fallback: string): void {
    error = fallback;
  }
</script>

<div
  class="relative flex h-dvh min-h-0 flex-col gap-3 rounded-2xl bg-gradient-to-br from-slate-100 via-slate-50
    to-stone-100 p-2 sm:h-[calc(100dvh-3rem)] sm:p-3"
>
  <PageTitle title="Top Up">
    <a
      id="payment-top-up-balance-link"
      href={resolve(PATH_PAYMENT)}
      class="flex h-9 items-center justify-center rounded-xl border border-white/80 bg-white/90 px-3
        text-sm font-medium text-slate-700 shadow-sm hover:bg-white"
    >
      Balance
    </a>
  </PageTitle>

  <section
    class="grid min-h-0 grow grid-cols-1 gap-3 overflow-y-auto rounded-2xl border border-white/70 bg-white/60
      p-3 shadow-[0_20px_45px_-25px_rgba(30,41,59,0.45)] backdrop-blur-md lg:grid-cols-[22rem_1fr]"
  >
    <form
      class="space-y-4 rounded-2xl border border-white/80 bg-white/80 p-4 shadow-sm"
      onsubmit={form.submit}
      inert={form.loading || undefined}
    >
      <div>
        <h2 class="text-base font-semibold text-slate-800">Amount</h2>
        <p class="mt-1 text-sm text-slate-500">
          {#if paymentConfig}
            {formatUsdMicros(minAmountMicros)} to {formatUsdMicros(maxAmountMicros)}
          {:else}
            Loading limits
          {/if}
        </p>
      </div>

      <div class="grid grid-cols-2 gap-2">
        {#each PRESET_AMOUNTS as amount (amount)}
          <Button
            id={`payment-top-up-preset-${amount}`}
            variant="secondary"
            active={form.selectedPreset.value === amount && !form.customAmount.value}
            class="h-11 rounded-xl px-3 text-sm font-semibold"
            onclick={() => selectPreset(amount)}
          >
            {formatUsdMicros(dollarsToUsdMicros(amount))}
          </Button>
        {/each}
      </div>

      <label class="block space-y-1">
        <span class="text-xs font-medium text-slate-500">Custom amount</span>
        <Input
          id="payment-top-up-custom-amount"
          type="number"
          min="1"
          step="0.01"
          placeholder="75.00"
          field={form.customAmount}
          disabled={loadingConfig}
        />
        <FieldError error={form.customAmount.error} />
      </label>

      <div
        id="payment-top-up-selected-amount"
        class="rounded-xl border border-white/80 bg-white/80 px-3 py-2 text-sm text-slate-600"
      >
        Selected: <span class="font-semibold text-slate-800">{formatUsdMicros(selectedAmountMicros)}</span>
      </div>

      <FieldError error={form.error} />

      <Button
        id="payment-top-up-continue"
        class="w-full"
        submit
        disabled={!paymentConfig || !amountValid || form.loading}
        spinner={form.loading}
      >
        Continue
      </Button>
    </form>

    <div class="min-h-[24rem] rounded-2xl border border-white/80 bg-white/80 p-4 shadow-sm">
      <div {@attach attachPaymentElementContainer} class="min-h-32"></div>

      {#if checkoutActions}
        <div class="mt-4">
          <Button id="payment-top-up-pay" class="w-full" onclick={confirmPayment} spinner={confirming}>Pay</Button>
        </div>
      {/if}

      {#if message}
        <div
          id="payment-top-up-message"
          class="text-sky-900 mt-4 rounded-xl border border-sky-200/80 bg-sky-50/90 px-3 py-2 text-sm"
        >
          {message}
        </div>
      {/if}

      {#if error}
        <div
          id="payment-top-up-error"
          class="text-amber-900 mt-4 rounded-xl border border-amber-200/80 bg-amber-100/90 px-3 py-2 text-sm"
        >
          {error}
        </div>
      {/if}
    </div>
  </section>
</div>

// src/routes/(app)/payment/top-up/+page.tsx
import { loadStripe, type StripeCheckoutLoadActionsSuccess, type StripePaymentElement } from "@stripe/stripe-js";
import { createMemo, createSignal, For, onSettled, Show } from "solid-js";
import { CreateTopupCheckoutSessionDocument, PaymentConfigDocument, type PaymentConfigQuery } from "~/gql/graphql";
import { PATH_PAYMENT } from "~/lib/app/paths";
import { Button, Input, PageTitle } from "~/components";
import { dollarsToUsdMicros, formatUsdMicros } from "~/lib/feature/payment/payment-display";
import { graphqlClient } from "~/lib/graphql/client";

type PaymentConfig = PaymentConfigQuery["paymentConfig"];
const presetAmounts = [10, 25, 50, 100];

export default function PaymentTopUpPage() {
  const [config, setConfig] = createSignal<PaymentConfig | null>(null);
  const [loading, setLoading] = createSignal(true);
  const [starting, setStarting] = createSignal(false);
  const [confirming, setConfirming] = createSignal(false);
  const [preset, setPreset] = createSignal(10);
  const [customAmount, setCustomAmount] = createSignal("");
  const [message, setMessage] = createSignal<string | null>(null);
  const [error, setError] = createSignal<string | null>(null);
  const [actions, setActions] = createSignal<StripeCheckoutLoadActionsSuccess | null>(null);
  let container: HTMLDivElement | undefined;
  let paymentElement: StripePaymentElement | null = null;
  const dollars = createMemo(() =>
    customAmount().trim() && Number.isFinite(Number(customAmount())) ? Number(customAmount()) : preset(),
  );
  const micros = createMemo(() => dollarsToUsdMicros(dollars()));
  const amountValid = createMemo(() =>
    Boolean(config() && micros() >= config()!.minTopupUsdMicros && micros() <= config()!.maxTopupUsdMicros),
  );

  onSettled(() => {
    void loadConfig();
    return () => paymentElement?.destroy();
  });

  async function loadConfig(): Promise<void> {
    setLoading(true);
    try {
      const response = await graphqlClient.query(PaymentConfigDocument, {}, { requestPolicy: "network-only" });
      if (response.error || !response.data) throw new Error();
      setConfig(response.data.paymentConfig);
      setError(null);
    } catch {
      setError("Could not load payment settings.");
    } finally {
      setLoading(false);
    }
  }

  async function startTopUp(): Promise<void> {
    const paymentConfig = config();
    if (!paymentConfig || !amountValid() || !container || starting()) return;
    setStarting(true);
    setMessage(null);
    setError(null);
    setActions(null);
    paymentElement?.destroy();
    paymentElement = null;
    try {
      const response = await graphqlClient.mutation(CreateTopupCheckoutSessionDocument, {
        input: { amountUsdMicros: micros() },
      });
      if (response.error || !response.data) throw new Error();
      const session = response.data.createTopupCheckoutSession;
      const stripe = await loadStripe(paymentConfig.stripePublishableKey);
      if (!stripe) {
        setError("Could not load Stripe.");
        return;
      }
      const checkout = stripe.initCheckoutElementsSdk({
        clientSecret: session.clientSecret,
        elementsOptions: { appearance: { theme: "stripe" } },
      });
      const element = checkout.createPaymentElement();
      const result = await checkout.loadActions();
      if (result.type === "error") {
        setError("Could not prepare payment.");
        return;
      }
      element.mount(container);
      paymentElement = element;
      setActions(result.actions);
      setMessage(`${formatUsdMicros(session.amountUsdMicros)} top up is ready.`);
    } catch {
      setError("Could not start top up.");
    } finally {
      setStarting(false);
    }
  }

  async function confirm(): Promise<void> {
    if (!actions() || confirming()) return;
    setConfirming(true);
    setError(null);
    setMessage(null);
    try {
      const result = await actions()!.confirm({ returnUrl: `${window.location.origin}${PATH_PAYMENT}` });
      if (result.type === "error") {
        setError("Could not confirm payment.");
        return;
      }
      setMessage("Payment submitted.");
    } catch {
      setError("Could not confirm payment.");
    } finally {
      setConfirming(false);
    }
  }

  return (
    <div class="relative flex h-dvh min-h-0 flex-col gap-3 rounded-2xl bg-gradient-to-br from-slate-100 via-slate-50 to-stone-100 p-2 sm:h-[calc(100dvh-3rem)] sm:p-3">
      <PageTitle title="Top Up">
        <a
          href={PATH_PAYMENT}
          class="flex h-9 items-center rounded-xl border border-white/80 bg-white/90 px-3 text-sm font-medium text-slate-700"
        >
          Balance
        </a>
      </PageTitle>
      <section class="grid min-h-0 grow gap-3 overflow-y-auto rounded-2xl border border-white/70 bg-white/60 p-3 shadow-xl lg:grid-cols-[22rem_1fr]">
        <form
          class="space-y-4 rounded-2xl border border-white/80 bg-white/80 p-4 shadow-sm"
          onSubmit={(event) => {
            event.preventDefault();
            void startTopUp();
          }}
        >
          <div>
            <h2 class="font-semibold text-slate-800">Amount</h2>
            <p class="mt-1 text-sm text-slate-500">
              <Show when={config()} fallback="Loading limits">
                {(value) =>
                  `${formatUsdMicros(value().minTopupUsdMicros)} to ${formatUsdMicros(value().maxTopupUsdMicros)}`
                }
              </Show>
            </p>
          </div>
          <div class="grid grid-cols-2 gap-2">
            <For each={presetAmounts}>
              {(amount) => (
                <Button
                  variant="secondary"
                  active={preset() === amount && !customAmount()}
                  class="h-11"
                  onClick={() => {
                    setPreset(amount);
                    setCustomAmount("");
                  }}
                >
                  {formatUsdMicros(dollarsToUsdMicros(amount))}
                </Button>
              )}
            </For>
          </div>
          <label class="block text-xs font-medium text-slate-500">
            Custom amount
            <Input
              type="number"
              min="1"
              step="0.01"
              value={customAmount()}
              disabled={loading()}
              onInput={(event) => setCustomAmount(event.currentTarget.value)}
            />
          </label>
          <div class="rounded-xl bg-white/80 px-3 py-2 text-sm text-slate-600">
            Selected: <strong>{formatUsdMicros(micros())}</strong>
          </div>
          <Button class="w-full" submit disabled={!amountValid()} spinner={starting()}>
            Continue
          </Button>
        </form>
        <div class="min-h-96 rounded-2xl border border-white/80 bg-white/80 p-4 shadow-sm">
          <div ref={container} class="min-h-32" />
          <Show when={actions()}>
            <Button class="mt-4 w-full" spinner={confirming()} onClick={() => void confirm()}>
              Pay
            </Button>
          </Show>
          <Show when={message()}>
            {(value) => (
              <div class="text-sky-900 mt-4 rounded-xl border border-sky-200 bg-sky-50 px-3 py-2 text-sm">
                {value()}
              </div>
            )}
          </Show>
          <Show when={error()}>
            {(value) => (
              <div class="text-amber-900 mt-4 rounded-xl border border-amber-200 bg-amber-100 px-3 py-2 text-sm">
                {value()}
              </div>
            )}
          </Show>
        </div>
      </section>
    </div>
  );
}
