// src/routes/reset-password/components/EmailSection.tsx
import { createSignal } from "solid-js";
import { SendPasswordResetCodeDocument } from "~/gql/graphql";
import { Button, Field, FieldError, FieldLabel, Input } from "~/components";
import { defaultErrorText, networkErrorText, toErrorText } from "~/lib/form/errors";
import { OTP_LENGTH } from "~/lib/form/validators";
import { graphqlClient } from "~/lib/graphql/client";
import { graphQLErrorCode } from "~/lib/graphql/errors";
import { showError, showInfo } from "~/lib/state/notifications";
import { createCountdown } from "~/lib/utils/countdown";
import { EmailSchema, type ResetPasswordFieldProps } from "../form";

export function EmailSection(props: ResetPasswordFieldProps) {
  const [codeLoading, setCodeLoading] = createSignal(false);
  const countdown = createCountdown();

  async function sendCode(): Promise<void> {
    const result = EmailSchema.safeParse(props.values.email);
    if (!result.success) {
      props.setError("email", result.error.issues[0]?.message ?? defaultErrorText);
      return;
    }

    props.setError("email", undefined);
    setCodeLoading(true);
    try {
      const response = await graphqlClient.mutation(SendPasswordResetCodeDocument, { email: props.values.email });
      if (!response.error && response.data?.sendPasswordResetCode) {
        countdown.start(60);
        showInfo("If an account exists for that email, a reset code has been sent.");
        return;
      }
      showError(toErrorText(graphQLErrorCode(response.error)));
    } catch {
      showError(networkErrorText);
    } finally {
      setCodeLoading(false);
    }
  }

  return (
    <>
      <Field>
        <FieldLabel for="email">E-mail</FieldLabel>
        <Input
          id="email"
          value={props.values.email}
          onInput={(event) => props.setValue("email", event.currentTarget.value)}
          type="email"
          autocomplete="email"
          placeholder="you@example.com"
          error={props.errors.email}
        />
        <FieldError error={props.errors.email} />
      </Field>
      <Field class="mt-4">
        <FieldLabel for="reset-code">Reset code</FieldLabel>
        <Input
          id="reset-code"
          value={props.values.code}
          onInput={(event) => props.setValue("code", event.currentTarget.value)}
          maxlength={OTP_LENGTH}
          inputmode="numeric"
          autocomplete="one-time-code"
          error={props.errors.code}
          rightAddon={
            <Button
              id="reset-password-code-send"
              class="min-w-24 px-3 text-xs tracking-[0.02em]"
              variant="secondary"
              small
              spinner={codeLoading()}
              disabled={codeLoading() || countdown.remainingSeconds() > 0}
              onClick={() => void sendCode()}
            >
              {countdown.remainingSeconds() === 0 ? "Send code" : countdown.remainingSeconds()}
            </Button>
          }
        />
        <FieldError error={props.errors.code} />
      </Field>
    </>
  );
}

// src/routes/reset-password/components/EmailSection.svelte
<script lang="ts">
  import { SendPasswordResetCodeStore } from "$houdini";
  import { Button, Field, FieldError, FieldLabel, Input } from "$lib";
  import { defaultErrorText, networkErrorText, toErrorText } from "$lib/form/errors";
  import { OTP_LENGTH } from "$lib/form/validators";
  import { graphQLErrorCode } from "$lib/graphql/errors";
  import { Countdown } from "$lib/utils/countdown.svelte";
  import { onDestroy } from "svelte";
  import { getNotificationsState } from "$lib/state/notifications.svelte";
  import { EmailSchema, getResetPasswordForm } from "../form.svelte";
  const notificationsState = getNotificationsState();
  const form = getResetPasswordForm();

  let { email, code } = form;

  let codeLoading = $state(false);

  const countdown = new Countdown();
  const sendPasswordResetCodeMutation = new SendPasswordResetCodeStore();

  async function sendCodeClick(): Promise<void> {
    const emailResult = EmailSchema.safeParse(email.value);

    if (!emailResult.success) {
      email.error = emailResult.error.issues[0]?.message ?? defaultErrorText;
      return;
    }

    email.error = null;
    codeLoading = true;

    try {
      const response = await sendPasswordResetCodeMutation.mutate({ email: email.value });

      if (!response.errors && response.data?.sendPasswordResetCode) {
        countdown.start(60);
        notificationsState.showInfo("If an account exists for that email, a reset code has been sent.");
        return;
      }

      notificationsState.showError(toErrorText(graphQLErrorCode(response.errors)));
    } catch {
      notificationsState.showError(networkErrorText);
    } finally {
      codeLoading = false;
    }
  }

  onDestroy(() => {
    countdown.stop();
  });
</script>

<Field>
  <FieldLabel for="email">E-mail</FieldLabel>
  <Input id="email" field={email} type="email" autocomplete="email" placeholder="you@example.com" />
  <FieldError error={email.error} />
</Field>

<Field class="mt-4">
  <FieldLabel for="reset-code">Reset code</FieldLabel>
  <Input id="reset-code" field={code} maxlength={OTP_LENGTH} inputmode="numeric" autocomplete="one-time-code">
    {#snippet rightAddon()}
      <Button
        id="reset-password-code-send"
        class="min-w-24 px-3 text-xs tracking-[0.02em]"
        variant="secondary"
        small
        spinner={codeLoading}
        disabled={codeLoading || countdown.remainingSeconds > 0}
        onclick={() => void sendCodeClick()}
      >
        {countdown.remainingSeconds === 0 ? "Send code" : countdown.remainingSeconds}
      </Button>
    {/snippet}
  </Input>
  <FieldError error={code.error} />
</Field>
