// src/routes/(app)/contact-group/components/ContactGroupFormPage.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { onMount } from "svelte";
  import { Button, Field, FieldError, FieldLabel, Input, PageTitle } from "$lib";
  import { PATH_CONTACT_GROUP } from "$lib/app/paths";
  import type { ErrorResponse, Ulid } from "$lib/api/index.schemas";
  import { createContactGroup, getContactGroup, updateContactGroup } from "$lib/api/contact-group/contact-group";
  import { networkErrorText, toErrorText } from "$lib/form/errors";
  import { notificationsState } from "$lib/state/notifications.svelte";

  type FormMode = "create" | "edit";

  interface Props {
    id?: string;
    mode: FormMode;
  }

  let { id, mode }: Props = $props();

  let name = $state("");
  let initialName = $state("");
  let nameError = $state<string | null>(null);
  let formError = $state<string | null>(null);
  let loadingContactGroup = $state(false);
  let saving = $state(false);

  const title = $derived(mode === "create" ? "Add contact group" : "Edit contact group");
  const submitLabel = $derived(mode === "create" ? "Create" : "Save");
  const nameDirty = $derived(name.trim() !== initialName);
  const submitDisabled = $derived(saving || loadingContactGroup || (mode === "edit" && !nameDirty));

  onMount(() => {
    if (mode === "edit") {
      loadingContactGroup = true;
      void loadContactGroup();
    }
  });

  function getResponseError(error?: ErrorResponse): string {
    return error?.errorDescription ?? toErrorText(error?.errorCode);
  }

  function validate(): boolean {
    nameError = null;
    formError = null;

    if (!name.trim()) {
      nameError = "Required";
      return false;
    }

    return true;
  }

  async function loadContactGroup(): Promise<void> {
    if (!id) {
      formError = "Contact group was not found.";
      loadingContactGroup = false;
      return;
    }

    try {
      const response = await getContactGroup(id as Ulid, { credentials: "include" });

      if (response.status !== 200) {
        formError = getResponseError(response.data);
        return;
      }

      name = response.data.name;
      initialName = response.data.name.trim();
    } catch {
      formError = networkErrorText;
    } finally {
      loadingContactGroup = false;
    }
  }

  async function submit(event: SubmitEvent): Promise<void> {
    event.preventDefault();

    if (!validate()) {
      return;
    }

    saving = true;

    try {
      if (mode === "create") {
        await submitCreateContactGroup();
      } else {
        await submitUpdateContactGroup();
      }
    } catch {
      formError = networkErrorText;
    } finally {
      saving = false;
    }
  }

  async function submitCreateContactGroup(): Promise<void> {
    const response = await createContactGroup({ name: name.trim() }, { credentials: "include" });

    if (response.status === 200) {
      notificationsState.showInfo("Contact group has been created");
      await goto(PATH_CONTACT_GROUP);
      return;
    }

    formError = getResponseError(response.data);
  }

  async function submitUpdateContactGroup(): Promise<void> {
    if (!id) {
      formError = "Contact group was not found.";
      return;
    }

    const response = await updateContactGroup(id as Ulid, { name: name.trim() }, { credentials: "include" });

    if (response.status === 200) {
      notificationsState.showInfo("Contact group has been updated");
      await goto(PATH_CONTACT_GROUP);
      return;
    }

    formError = getResponseError(response.data);
  }
</script>

<div
  class="flex h-dvh min-h-0 flex-col rounded-2xl bg-gradient-to-br from-slate-100 via-slate-50
    to-stone-100 p-2 sm:h-[calc(100dvh-3rem)] sm:p-3"
>
  <PageTitle {title}>
    <a
      href={PATH_CONTACT_GROUP}
      class="flex h-9 items-center justify-center rounded-xl border border-white/80 bg-white/80 px-3
        text-base font-medium text-slate-700 shadow-sm backdrop-blur-sm hover:bg-white"
    >
      Back
    </a>
  </PageTitle>

  <div class="flex min-h-0 grow items-center justify-center pb-18">
    <section
      class="w-full max-w-xl rounded-2xl border border-white/80 bg-white/75 p-4
        shadow-[0_20px_45px_-25px_rgba(30,41,59,0.45)] backdrop-blur-md sm:p-6"
    >
      <form onsubmit={submit} inert={saving || loadingContactGroup || undefined}>
        <Field>
          <FieldLabel for="contact-group-name">Name</FieldLabel>
          <Input
            id="contact-group-name"
            bind:value={name}
            maxlength={100}
            placeholder="Newsletter subscribers"
            error={nameError}
          />
          <FieldError error={nameError} />
        </Field>

        <FieldError class="mt-3" error={formError} />

        <div class="mt-5 flex justify-end gap-2">
          <a
            href={PATH_CONTACT_GROUP}
            class="flex h-9 items-center justify-center rounded-xl border border-white/80 bg-white/80 px-3
              text-base font-medium text-slate-700 shadow-sm backdrop-blur-sm hover:bg-white"
          >
            Cancel
          </a>
          <Button submit spinner={saving} disabled={submitDisabled}>{submitLabel}</Button>
        </div>
      </form>
    </section>
  </div>
</div>

// src/routes/(app)/contact-group/(form)/ContactGroupFormPage.tsx
import { useNavigate, useParams } from "@solidjs/router";
import { createSignal, onSettled, Show } from "solid-js";
import {
  ContactGroupFormEditQueryDocument,
  CreateContactGroupDocument,
  UpdateContactGroupDocument,
} from "~/gql/graphql";
import { PATH_CONTACT_GROUP } from "~/lib/app/paths";
import { Button, Card, Field, FieldError, FieldLabel, Input, PageTitle } from "~/components";
import { defaultErrorText, networkErrorText } from "~/lib/form/errors";
import { graphqlClient } from "~/lib/graphql/client";
import { showInfo } from "~/lib/state/notifications";

export function ContactGroupFormPage(props: { mode: "create" | "edit" }) {
  const navigate = useNavigate();
  const params = useParams<{ id?: string }>();
  const [name, setName] = createSignal("");
  const [nameError, setNameError] = createSignal<string | null>(null);
  const [formError, setFormError] = createSignal<string | null>(null);
  const [loadError, setLoadError] = createSignal<string | null>(null);
  const [loading, setLoading] = createSignal(props.mode === "edit");
  const [submitting, setSubmitting] = createSignal(false);

  onSettled(() => {
    if (props.mode === "edit") void loadGroup();
  });
  async function loadGroup(): Promise<void> {
    setLoading(true);
    setLoadError(null);
    try {
      if (!params.id) {
        setLoadError("Contact group was not found.");
        return;
      }
      const response = await graphqlClient.query(
        ContactGroupFormEditQueryDocument,
        { id: params.id },
        { requestPolicy: "network-only" },
      );
      if (response.error || !response.data?.contactGroup) {
        setLoadError(defaultErrorText);
        return;
      }
      setName(response.data.contactGroup.name);
    } catch {
      setLoadError(networkErrorText);
    } finally {
      setLoading(false);
    }
  }
  async function submit(event: SubmitEvent): Promise<void> {
    event.preventDefault();
    setNameError(null);
    setFormError(null);
    const normalizedName = name().trim();
    if (!normalizedName) {
      setNameError("Required");
      return;
    }
    setSubmitting(true);
    try {
      const response =
        props.mode === "create"
          ? await graphqlClient.mutation(CreateContactGroupDocument, { input: { name: normalizedName } })
          : await graphqlClient.mutation(UpdateContactGroupDocument, {
              id: params.id!,
              input: { name: normalizedName },
            });
      if (response.error) {
        setFormError(defaultErrorText);
        return;
      }
      showInfo(props.mode === "create" ? "Contact group has been created" : "Contact group has been updated");
      navigate(PATH_CONTACT_GROUP);
    } catch {
      setFormError(networkErrorText);
    } finally {
      setSubmitting(false);
    }
  }
  return (
    <div class="flex h-dvh min-h-0 flex-col rounded-2xl bg-linear-to-br from-slate-100 via-slate-50 to-stone-100 p-2 sm:h-[calc(100dvh-3rem)] sm:p-3">
      <PageTitle title={props.mode === "create" ? "Add contact group" : "Edit contact group"}>
        <Button variant="secondary" onClick={() => window.history.back()}>
          Back
        </Button>
      </PageTitle>
      <div class="flex min-h-0 grow justify-center overflow-y-auto pt-4 pb-18 sm:items-start">
        <Card variant="panel" class="w-full max-w-xl p-4 sm:p-6">
          <Show
            when={!loadError()}
            fallback={
              <div class="space-y-4 py-6 text-center">
                <FieldError error={loadError()} />
                <Button variant="secondary" onClick={() => void loadGroup()}>
                  Try again
                </Button>
              </div>
            }
          >
            <form onSubmit={submit} inert={submitting()}>
              <Field>
                <FieldLabel for="contact-group-name">Name</FieldLabel>
                <Input
                  id="contact-group-name"
                  value={name()}
                  onInput={(event) => setName(event.currentTarget.value)}
                  loading={loading()}
                  maxlength={100}
                  placeholder="Newsletter subscribers"
                  error={nameError()}
                />
                <FieldError error={nameError()} />
              </Field>
              <FieldError class="mt-3" error={formError()} />
              <div class="mt-5 flex justify-end gap-2">
                <Button variant="secondary" onClick={() => window.history.back()}>
                  Cancel
                </Button>
                <Button submit spinner={submitting()} disabled={loading() || submitting()}>
                  {props.mode === "create" ? "Add Contact Group" : "Update Contact Group"}
                </Button>
              </div>
            </form>
          </Show>
        </Card>
      </div>
    </div>
  );
}
