// src/lib/components/sidebar/PhoneFilter.svelte
<script lang="ts">
  import { SidebarPhoneNumbersStore } from "$houdini";
  import { onMount } from "svelte";
  import { Select, type DropdownOption } from "$lib";
  import { formatPhoneNumber } from "$lib/feature/phone/phone-display";
  import Phone from "text-reach-frontend-library/icons/Phone.svelte";
  import { phoneFilterState } from "$lib/state/phone-filter.svelte";

  const allPhonesOption: DropdownOption<string | null> = { id: null, value: "All phones" };
  const phoneNumbersQuery = new SidebarPhoneNumbersStore();

  let loading = $state(true);
  let loadError = $state<string | null>(null);

  const options = $derived<DropdownOption<string | null>[]>([
    allPhonesOption,
    ...($phoneNumbersQuery.data?.tenantPhones.edges ?? []).map(({ node }) => ({
      id: node.id,
      value: formatPhoneNumber(node.phoneNumber),
    })),
  ]);
  const selectedOption = $derived(
    options.find((option) => option.id === phoneFilterState.selectedPhoneId) ?? allPhonesOption,
  );

  onMount(() => {
    void loadPhones();
  });

  async function loadPhones(): Promise<void> {
    loading = true;
    loadError = null;

    try {
      const response = await phoneNumbersQuery.fetch();
      if (response.errors || !response.data) {
        phoneFilterState.reset();
        loadError = "Phone numbers unavailable.";
        return;
      }

      const availablePhoneIds = new Set(response.data.tenantPhones.edges.map(({ node }) => node.id));
      if (phoneFilterState.selectedPhoneId && !availablePhoneIds.has(phoneFilterState.selectedPhoneId)) {
        phoneFilterState.reset();
      }
    } catch {
      phoneFilterState.reset();
      loadError = "Phone numbers unavailable.";
    } finally {
      loading = false;
    }
  }
</script>

<Select
  label="Phone number"
  inputId="global-phone-filter"
  {options}
  value={selectedOption}
  {loading}
  error={loadError}
  onChange={(option) => phoneFilterState.selectPhone(option.id)}
  aria-label="Filter the app by phone number"
>
  {#snippet leftAddon()}
    <Phone class="size-4 shrink-0 fill-slate-500" />
  {/snippet}
</Select>

// src/components/sidebar/PhoneFilter.tsx
import { createMemo, createSignal, For, onSettled, Show } from "solid-js";
import { SidebarPhoneNumbersDocument } from "~/gql/graphql";
import { formatPhoneNumber } from "~/lib/feature/phone/phone-display";
import { Phone } from "~/lib/icons";
import { graphqlClient } from "~/lib/graphql/client";
import { resetPhoneFilter, selectedPhoneId, selectPhone } from "~/lib/state/phone-filter";

interface PhoneOption {
  id: string;
  value: string;
}

export function PhoneFilter() {
  const [loading, setLoading] = createSignal(true);
  const [loadError, setLoadError] = createSignal<string | null>(null);
  const [phoneOptions, setPhoneOptions] = createSignal<PhoneOption[]>([]);
  const options = createMemo(() => [{ id: "", value: "All phones" }, ...phoneOptions()]);

  onSettled(() => {
    void (async () => {
      setLoading(true);
      setLoadError(null);
      try {
        const response = await graphqlClient.query(SidebarPhoneNumbersDocument, {}, { requestPolicy: "network-only" });
        if (response.error || !response.data) {
          resetPhoneFilter();
          setLoadError("Phone numbers unavailable.");
          return;
        }

        const nextOptions = response.data.tenantPhones.edges.map(({ node }) => ({
          id: node.id,
          value: formatPhoneNumber(node.phoneNumber),
        }));
        setPhoneOptions(nextOptions);
        if (selectedPhoneId() && !nextOptions.some((option) => option.id === selectedPhoneId())) {
          resetPhoneFilter();
        }
      } catch {
        resetPhoneFilter();
        setLoadError("Phone numbers unavailable.");
      } finally {
        setLoading(false);
      }
    })();
  });

  return (
    <label class="block text-xs font-medium text-slate-600" for="global-phone-filter">
      Phone number
      <div class="glass-input mt-1 flex items-center gap-2 px-2">
        <Phone class="size-4 shrink-0 fill-slate-500" />
        <select
          id="global-phone-filter"
          class="min-w-0 grow bg-transparent py-2 text-sm text-slate-700 outline-none"
          disabled={loading()}
          value={selectedPhoneId() ?? ""}
          onChange={(event) => selectPhone(event.currentTarget.value || null)}
          aria-label="Filter the app by phone number"
        >
          <For each={options()}>{(option) => <option value={option.id}>{option.value}</option>}</For>
        </select>
      </div>
      <Show when={loadError()}>{(error) => <span class="mt-1 block text-xs text-rose-600">{error()}</span>}</Show>
    </label>
  );
}
