// src/routes/(app)/phone/10dlc/+page.svelte
<script lang="ts">
  import { resolve } from "$app/paths";
  import { onMount } from "svelte";
  import { TenDlcBrandStore, TenDlcCampaignsStore } from "$houdini";
  import { Alert, BackButton, Button, Card, PageTitle } from "$lib";
  import { PATH_PHONE_BUY, PATH_TEN_DLC_BRAND, PATH_TEN_DLC_CAMPAIGN_ADD } from "$lib/app/paths";
  import { isActiveTenDlcCampaignStatus, tenDlcStatusLabel } from "$lib/feature/phone/ten-dlc-display";
  import { graphQLErrorCode } from "$lib/graphql/errors";

  const brandQuery = new TenDlcBrandStore();
  const campaignsQuery = new TenDlcCampaignsStore();

  let loading = $state(true);
  let loadError = $state<string | null>(null);
  let brandMissing = $state(false);
  const brand = $derived($brandQuery.data?.tenDlcBrand ?? null);
  const campaigns = $derived($campaignsQuery.data?.tenDlcCampaigns.edges.map((edge) => edge.node) ?? []);
  const activeCampaigns = $derived(
    campaigns.filter((campaign) => isActiveTenDlcCampaignStatus(campaign.providerStatus)),
  );

  onMount(() => {
    void loadRegistration();
  });

  async function loadRegistration(): Promise<void> {
    loading = true;
    loadError = null;
    brandMissing = false;

    try {
      const brandResponse = await brandQuery.fetch();
      if (brandResponse.errors) {
        if (graphQLErrorCode(brandResponse.errors) === "NOT_FOUND") {
          brandMissing = true;
          return;
        }
        loadError = "There was an error.";
        return;
      }

      const campaignResponse = await campaignsQuery.fetch();
      if (campaignResponse.errors) loadError = "There was an error.";
    } catch {
      loadError = "Please check your internet connection and try again.";
    } finally {
      loading = false;
    }
  }
</script>

<div
  class="flex h-dvh min-h-0 flex-col rounded-2xl bg-linear-to-br from-slate-100 via-slate-50
    to-stone-100 p-2 sm:h-[calc(100dvh-3rem)] sm:p-3"
>
  <PageTitle title="10DLC registration">
    <BackButton />
  </PageTitle>

  <div class="min-h-0 grow overflow-y-auto pb-[max(4.5rem,env(safe-area-inset-bottom))]">
    <div class="mx-auto grid max-w-5xl gap-3 lg:grid-cols-[20rem_minmax(0,1fr)]">
      <Card variant="panel" class="h-fit p-4 sm:p-5">
        <p class="text-xs font-semibold tracking-[0.06em] text-slate-500 uppercase">Brand</p>
        {#if loading}
          <div class="skeleton-loading mt-3 h-24 rounded-xl"></div>
        {:else if brandMissing}
          <h2 class="mt-2 text-lg font-semibold text-slate-800">Register your business brand</h2>
          <p class="mt-2 text-sm leading-6 text-slate-500">
            We use your saved legal business and authorized-contact information for carrier registration.
          </p>
          <a
            id="ten-dlc-brand-start"
            href={resolve(PATH_TEN_DLC_BRAND)}
            class="mt-4 flex h-10 items-center justify-center rounded-xl bg-slate-700 px-3 text-sm font-medium
              text-white shadow-sm hover:bg-slate-800">Register brand</a
          >
        {:else if brand}
          <h2 id="ten-dlc-brand-name" class="mt-2 text-lg font-semibold text-slate-800">{brand.name}</h2>
          <p class="mt-2 text-sm text-slate-500">Status: {tenDlcStatusLabel(brand.providerStatus)}</p>
        {/if}
      </Card>

      <Card variant="panel" class="p-4 sm:p-5">
        <div class="flex flex-wrap items-start justify-between gap-3">
          <div>
            <p class="text-xs font-semibold tracking-[0.06em] text-slate-500 uppercase">Campaigns</p>
            <h2 class="mt-1 text-lg font-semibold text-slate-800">Messaging use cases</h2>
          </div>
          {#if brand && !loadError}
            <a
              id="ten-dlc-campaign-add"
              href={resolve(PATH_TEN_DLC_CAMPAIGN_ADD)}
              class="flex h-9 items-center justify-center rounded-xl bg-slate-700 px-3 text-sm font-medium text-white
                shadow-sm hover:bg-slate-800">Register campaign</a
            >
          {/if}
        </div>

        {#if loadError}
          <div class="mt-4 space-y-3">
            <Alert type="error" layout="inline">{loadError}</Alert>
            <Button variant="secondary" onclick={loadRegistration}>Try again</Button>
          </div>
        {:else if loading}
          <div class="mt-4 grid gap-3">
            {#each Array(2) as _, index (index)}
              <div class="skeleton-loading h-24 rounded-2xl"></div>
            {/each}
          </div>
        {:else if !brandMissing && campaigns.length === 0}
          <div class="mt-4 rounded-2xl border border-dashed border-slate-300 bg-white/50 px-4 py-10 text-center">
            <p class="font-medium text-slate-700">No registered campaigns</p>
            <p class="mt-1 text-sm text-slate-500">Register how customers opt in and what messages they receive.</p>
          </div>
        {:else if campaigns.length > 0}
          <div class="mt-4 grid gap-3">
            {#each campaigns as campaign (campaign.id)}
              <article
                id={`ten-dlc-campaign-${campaign.id}`}
                class="rounded-2xl border border-white/80 bg-white/80 p-4"
              >
                <div class="flex flex-wrap items-start justify-between gap-2">
                  <div>
                    <p class="font-semibold text-slate-800">{campaign.description}</p>
                    <p class="mt-1 text-xs text-slate-500">{campaign.usecase.replaceAll("_", " ")}</p>
                  </div>
                  <span
                    class={[
                      "rounded-full px-2.5 py-1 text-xs font-medium",
                      isActiveTenDlcCampaignStatus(campaign.providerStatus)
                        ? "bg-emerald-100 text-emerald-700"
                        : "text-amber-700 bg-amber-100",
                    ]}>{tenDlcStatusLabel(campaign.providerStatus)}</span
                  >
                </div>
              </article>
            {/each}
          </div>
        {/if}

        {#if activeCampaigns.length > 0}
          <a id="ten-dlc-buy-number" href={resolve(PATH_PHONE_BUY)} class="mt-4 inline-block text-sm font-medium">
            Buy a 10DLC number
          </a>
        {/if}
      </Card>
    </div>
  </div>
</div>

// src/routes/(app)/phone/10dlc/+page.tsx
import { createSignal, For, onSettled, Show } from "solid-js";
import {
  TenDlcBrandDocument,
  TenDlcCampaignsDocument,
  type TenDlcBrandQuery,
  type TenDlcCampaignsQuery,
} from "~/gql/graphql";
import { PATH_PHONE, PATH_PHONE_BUY, PATH_TEN_DLC_BRAND, PATH_TEN_DLC_CAMPAIGN_ADD } from "~/lib/app/paths";
import { Alert, Button, Card, PageTitle } from "~/components";
import { isActiveTenDlcCampaignStatus, tenDlcStatusLabel } from "~/lib/feature/phone/phone-display";
import { graphqlClient } from "~/lib/graphql/client";
import { graphQLErrorCode } from "~/lib/graphql/errors";
import { hasAccess } from "~/lib/state/session";
type Brand = TenDlcBrandQuery["tenDlcBrand"];
type Campaign = TenDlcCampaignsQuery["tenDlcCampaigns"]["edges"][number]["node"];
export default function TenDlcPage() {
  const [brand, setBrand] = createSignal<Brand | null>(null);
  const [campaigns, setCampaigns] = createSignal<Campaign[]>([]);
  const [missing, setMissing] = createSignal(false);
  const [loading, setLoading] = createSignal(true);
  const [error, setError] = createSignal<string | null>(null);
  onSettled(() => void load());
  async function load(): Promise<void> {
    setLoading(true);
    setError(null);
    setMissing(false);
    try {
      const brandResult = await graphqlClient.query(TenDlcBrandDocument, {}, { requestPolicy: "network-only" });
      if (brandResult.error) {
        if (graphQLErrorCode(brandResult.error) === "NOT_FOUND") {
          setMissing(true);
          return;
        }
        throw new Error();
      }
      setBrand(brandResult.data?.tenDlcBrand ?? null);
      const campaignResult = await graphqlClient.query(TenDlcCampaignsDocument, {}, { requestPolicy: "network-only" });
      if (campaignResult.error || !campaignResult.data) throw new Error();
      setCampaigns(campaignResult.data.tenDlcCampaigns.edges.map((edge) => edge.node));
    } catch {
      setError("Could not load 10DLC registration.");
    } finally {
      setLoading(false);
    }
  }
  return (
    <div class="flex h-dvh min-h-0 flex-col rounded-2xl bg-gradient-to-br from-slate-100 via-slate-50 to-stone-100 p-2 sm:h-[calc(100dvh-3rem)] sm:p-3">
      <PageTitle title="10DLC registration">
        <a href={PATH_PHONE} class="text-sm font-medium text-sky-700">
          Phone numbers
        </a>
      </PageTitle>
      <div class="min-h-0 grow overflow-y-auto pb-18">
        <div class="mx-auto grid max-w-5xl gap-3 lg:grid-cols-[20rem_minmax(0,1fr)]">
          <Card variant="panel" class="h-fit p-5">
            <p class="text-xs font-semibold text-slate-500 uppercase">Brand</p>
            <Show when={!loading()} fallback={<div class="skeleton-loading mt-3 h-24 rounded-xl" />}>
              <Show
                when={!missing()}
                fallback={
                  <>
                    <h2 class="mt-2 text-lg font-semibold">Register your business brand</h2>
                    <Show when={hasAccess("PHONE_WRITE")}>
                      <a href={PATH_TEN_DLC_BRAND} class="mt-4 block text-sm font-medium text-sky-700">
                        Register brand
                      </a>
                    </Show>
                  </>
                }
              >
                <Show when={brand()}>
                  {(value) => (
                    <>
                      <h2 class="mt-2 text-lg font-semibold">{value().name}</h2>
                      <p class="mt-2 text-sm text-slate-500">Status: {tenDlcStatusLabel(value().providerStatus)}</p>
                    </>
                  )}
                </Show>
              </Show>
            </Show>
          </Card>
          <Card variant="panel" class="p-5">
            <div class="flex justify-between gap-3">
              <div>
                <p class="text-xs font-semibold text-slate-500 uppercase">Campaigns</p>
                <h2 class="mt-1 text-lg font-semibold">Messaging use cases</h2>
              </div>
              <Show when={brand() && hasAccess("PHONE_WRITE")}>
                <a href={PATH_TEN_DLC_CAMPAIGN_ADD} class="text-sm font-medium text-sky-700">
                  Register campaign
                </a>
              </Show>
            </div>
            <Show when={error()}>
              {(value) => (
                <div class="mt-4">
                  <Alert type="error" layout="inline">
                    {value()}
                  </Alert>
                  <Button class="mt-3" variant="secondary" onClick={() => void load()}>
                    Try again
                  </Button>
                </div>
              )}
            </Show>
            <div class="mt-4 grid gap-3">
              <For
                each={campaigns()}
                fallback={
                  <p class="rounded-xl border border-dashed p-8 text-center text-sm text-slate-500">
                    No registered campaigns
                  </p>
                }
              >
                {(campaign) => (
                  <article class="rounded-2xl border border-white/80 bg-white/80 p-4">
                    <div class="flex justify-between gap-2">
                      <div>
                        <p class="font-semibold">{campaign.description}</p>
                        <p class="mt-1 text-xs text-slate-500">{campaign.usecase.replaceAll("_", " ")}</p>
                      </div>
                      <span class="text-xs font-medium">{tenDlcStatusLabel(campaign.providerStatus)}</span>
                    </div>
                  </article>
                )}
              </For>
            </div>
            <Show
              when={
                campaigns().some((campaign) => isActiveTenDlcCampaignStatus(campaign.providerStatus)) &&
                hasAccess("PHONE_WRITE")
              }
            >
              <a href={PATH_PHONE_BUY} class="mt-4 inline-block text-sm font-medium text-sky-700">
                Buy a 10DLC number
              </a>
            </Show>
          </Card>
        </div>
      </div>
    </div>
  );
}
