// src/routes/(app)/smart-group/+page.tsx
import { AppPlaceholderPage } from "text-reach-frontend-library/components";

export default function SmartGroupPage() {
  return (
    <AppPlaceholderPage
      title="Smart Groups"
      description="This page is available from the contact section and is ready for smart-group content."
    />
  );
}

// src/routes/(app)/smart-group/+page.svelte
<script lang="ts">
  import AppPlaceholderPage from "text-reach-frontend-library/components/app-placeholder/AppPlaceholderPage.svelte";
</script>

<AppPlaceholderPage
  title="Smart Groups"
  description="This route is here so the migrated sidebar works end-to-end while the smart groups screen is ported."
/>
