// src/routes/(app)/phone/10dlc/campaign/(form)/(routes)/add/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { resolve } from "$app/paths";
  import { onMount } from "svelte";
  import { cache, CreateTenDlcCampaignStore, TenDlcCampaignBrandStore } from "$houdini";
  import {
    Alert,
    BackButton,
    Button,
    Card,
    Field,
    FieldError,
    FieldLabel,
    Input,
    PageTitle,
    Select,
    TextArea,
  } from "$lib";
  import { PATH_TEN_DLC } from "$lib/app/paths";
  import { networkErrorText } from "$lib/form/errors";
  import type { FormSubmitResult } from "$lib/form/form.svelte";
  import { tenDlcStatusLabel } from "$lib/feature/phone/ten-dlc-display";
  import { notificationsState } from "text-reach-frontend-library/state/notifications.svelte";
  import SupportingDocumentField from "../../components/SupportingDocumentField.svelte";
  import { createTenDlcCampaignForm, type SubmitValues } from "../../components/form/form.svelte";

  const usecaseOptions = [
    { id: "MIXED", value: "Mixed messaging" },
    { id: "CUSTOMER_CARE", value: "Customer care" },
    { id: "DELIVERY_NOTIFICATION", value: "Delivery notifications" },
    { id: "ACCOUNT_NOTIFICATION", value: "Account notifications" },
    { id: "2FA", value: "Two-factor authentication" },
    { id: "MARKETING", value: "Marketing" },
    { id: "LOW_VOLUME_MIXED", value: "Low-volume mixed" },
    { id: "PUBLIC_SERVICE_ANNOUNCEMENT", value: "Public service announcements" },
    { id: "SECURITY_ALERT", value: "Security alerts" },
    { id: "SOLE_PROPRIETOR", value: "Sole proprietor" },
  ];

  const brandQuery = new TenDlcCampaignBrandStore();
  const createCampaignMutation = new CreateTenDlcCampaignStore();
  const form = createTenDlcCampaignForm(submit);

  let loading = $state(true);
  let loadError = $state<string | null>(null);
  const brand = $derived($brandQuery.data?.tenDlcBrand ?? null);
  const selectedUsecase = $derived(usecaseOptions.find((option) => option.id === form.usecase.value));
  const brandVerified = $derived(
    !brand?.providerStatus || ["VERIFIED", "VETTED_VERIFIED"].includes(brand.providerStatus.toUpperCase()),
  );

  onMount(() => {
    void loadBrand();
  });

  async function loadBrand(): Promise<void> {
    loading = true;
    loadError = null;
    try {
      const response = await brandQuery.fetch();
      if (response.errors || !response.data?.tenDlcBrand)
        loadError = "Register a 10DLC brand before adding a campaign.";
    } catch {
      loadError = networkErrorText;
    } finally {
      loading = false;
    }
  }

  async function submit(input: SubmitValues): Promise<FormSubmitResult> {
    try {
      const response = await createCampaignMutation.mutate({ input });
      if (response.errors || !response.data?.createTenDlcCampaign) return { error: "There was an error." };

      cache.markStale("TenDlcCampaignConnection");
      notificationsState.showInfo("10DLC campaign registration submitted");
      await goto(resolve(PATH_TEN_DLC));
      return {};
    } catch {
      return { error: networkErrorText };
    }
  }
</script>

<div
  class="flex h-dvh min-h-0 flex-col rounded-2xl bg-linear-to-br from-slate-100 via-slate-50
    to-stone-100 p-2 sm:h-[calc(100dvh-3rem)] sm:p-3"
>
  <PageTitle title="Register 10DLC campaign">
    <BackButton />
  </PageTitle>

  <div class="flex min-h-0 grow justify-center overflow-y-auto pt-2 pb-[max(4.5rem,env(safe-area-inset-bottom))]">
    <Card variant="panel" class="h-fit w-full max-w-4xl p-4 sm:p-6">
      {#if loadError}
        <div class="space-y-4 py-6 text-center">
          <Alert type="warning" layout="inline">{loadError}</Alert>
          <a href={resolve(PATH_TEN_DLC)} class="text-sm font-medium">Review 10DLC registration</a>
        </div>
      {:else if !loading && brand && !brandVerified}
        <div class="space-y-4 py-6 text-center">
          <Alert type="warning" layout="inline">
            {brand.name} is {tenDlcStatusLabel(brand.providerStatus).toLowerCase()}. Campaign registration is available
            after brand verification.
          </Alert>
          <a href={resolve(PATH_TEN_DLC)} class="text-sm font-medium">Review brand status</a>
        </div>
      {:else}
        <form onsubmit={form.submit} inert={form.loading || undefined} aria-busy={loading}>
          <section aria-labelledby="ten-dlc-usecase-heading">
            <h2 id="ten-dlc-usecase-heading" class="text-lg font-semibold text-slate-800">Messaging use case</h2>
            <p class="mt-1 text-sm text-slate-500">Describe exactly what customers consent to receive.</p>

            <div class="mt-4 grid gap-4 sm:grid-cols-2">
              <Field>
                <Select
                  inputId="ten-dlc-campaign-usecase"
                  label="Use case"
                  options={usecaseOptions}
                  value={selectedUsecase}
                  {loading}
                  error={form.usecase.error}
                  onChange={(option) => (form.usecase.value = option.id)}
                />
                <FieldError error={form.usecase.error} />
              </Field>
              <Field>
                <FieldLabel for="ten-dlc-campaign-description">Description</FieldLabel>
                <TextArea
                  id="ten-dlc-campaign-description"
                  bind:value={form.description.value}
                  {loading}
                  rows={4}
                  placeholder="Order confirmations and delivery updates for customers who opt in at checkout."
                />
                <FieldError error={form.description.error} />
              </Field>
            </div>
          </section>

          <section class="mt-6 border-t border-slate-200/80 pt-5" aria-labelledby="ten-dlc-consent-heading">
            <h2 id="ten-dlc-consent-heading" class="text-lg font-semibold text-slate-800">Consent and opt-in</h2>
            <div class="mt-4 grid gap-4 sm:grid-cols-2">
              <Field class="sm:col-span-2">
                <FieldLabel for="ten-dlc-campaign-message-flow">How customers opt in</FieldLabel>
                <TextArea
                  id="ten-dlc-campaign-message-flow"
                  bind:value={form.messageFlow.value}
                  {loading}
                  rows={4}
                  placeholder="Customers enter their number and check the SMS consent box during checkout."
                />
                <FieldError error={form.messageFlow.error} />
              </Field>
              <SupportingDocumentField
                bind:value={form.documentUrl.value}
                disabled={loading || form.loading}
                error={form.documentUrl.error}
              />
              <Field>
                <FieldLabel for="ten-dlc-campaign-opt-in-keywords">Opt-in keywords</FieldLabel>
                <Input id="ten-dlc-campaign-opt-in-keywords" bind:value={form.optInKeywords.value} {loading} />
              </Field>
            </div>
          </section>

          <section class="mt-6 border-t border-slate-200/80 pt-5" aria-labelledby="ten-dlc-samples-heading">
            <h2 id="ten-dlc-samples-heading" class="text-lg font-semibold text-slate-800">Message samples</h2>
            <div class="mt-4 grid gap-4 sm:grid-cols-2">
              <Field>
                <FieldLabel for="ten-dlc-campaign-sample-1">Sample message 1</FieldLabel>
                <TextArea id="ten-dlc-campaign-sample-1" bind:value={form.sampleMessage1.value} {loading} rows={4} />
                <FieldError error={form.sampleMessage1.error} />
              </Field>
              <Field>
                <FieldLabel for="ten-dlc-campaign-sample-2">Sample message 2</FieldLabel>
                <TextArea id="ten-dlc-campaign-sample-2" bind:value={form.sampleMessage2.value} {loading} rows={4} />
                <FieldError error={form.sampleMessage2.error} />
              </Field>
            </div>
          </section>

          <section class="mt-6 border-t border-slate-200/80 pt-5" aria-labelledby="ten-dlc-keywords-heading">
            <h2 id="ten-dlc-keywords-heading" class="text-lg font-semibold text-slate-800">Help and opt-out</h2>
            <div class="mt-4 grid gap-4 sm:grid-cols-2">
              <Field
                ><FieldLabel for="ten-dlc-campaign-help-keywords">Help keywords</FieldLabel><Input
                  id="ten-dlc-campaign-help-keywords"
                  bind:value={form.helpKeywords.value}
                  {loading}
                /></Field
              >
              <Field
                ><FieldLabel for="ten-dlc-campaign-opt-out-keywords">Opt-out keywords</FieldLabel><Input
                  id="ten-dlc-campaign-opt-out-keywords"
                  bind:value={form.optOutKeywords.value}
                  {loading}
                /></Field
              >
              <Field
                ><FieldLabel for="ten-dlc-campaign-help-message">Help response</FieldLabel><TextArea
                  id="ten-dlc-campaign-help-message"
                  bind:value={form.helpMessage.value}
                  {loading}
                  rows={3}
                /></Field
              >
              <Field
                ><FieldLabel for="ten-dlc-campaign-opt-out-message">Opt-out response</FieldLabel><TextArea
                  id="ten-dlc-campaign-opt-out-message"
                  bind:value={form.optoutMessage.value}
                  {loading}
                  rows={3}
                /></Field
              >
            </div>
          </section>

          <section class="mt-6 border-t border-slate-200/80 pt-5" aria-labelledby="ten-dlc-options-heading">
            <h2 id="ten-dlc-options-heading" class="text-lg font-semibold text-slate-800">Content declarations</h2>
            <div class="mt-4 grid gap-3 sm:grid-cols-2">
              <label class="flex min-h-11 items-center gap-3 rounded-xl bg-white/70 px-3 text-sm text-slate-700">
                <input
                  id="ten-dlc-campaign-embedded-link"
                  type="checkbox"
                  bind:checked={form.embeddedLink.value}
                  disabled={loading}
                  class="accent-sky-600 size-4"
                />
                Messages include links
              </label>
              <label class="flex min-h-11 items-center gap-3 rounded-xl bg-white/70 px-3 text-sm text-slate-700">
                <input
                  id="ten-dlc-campaign-embedded-phone"
                  type="checkbox"
                  bind:checked={form.embeddedPhone.value}
                  disabled={loading}
                  class="accent-sky-600 size-4"
                />
                Messages include phone numbers
              </label>
              <label class="flex min-h-11 items-center gap-3 rounded-xl bg-white/70 px-3 text-sm text-slate-700">
                <input
                  id="ten-dlc-campaign-number-pool"
                  type="checkbox"
                  bind:checked={form.numberPool.value}
                  disabled={loading}
                  class="accent-sky-600 size-4"
                />
                Campaign uses a number pool
              </label>
              <label class="flex min-h-11 items-center gap-3 rounded-xl bg-white/70 px-3 text-sm text-slate-700">
                <input
                  id="ten-dlc-campaign-age-gated"
                  type="checkbox"
                  bind:checked={form.ageGated.value}
                  disabled={loading}
                  class="accent-sky-600 size-4"
                />
                Content is age-gated
              </label>
              <label class="flex min-h-11 items-center gap-3 rounded-xl bg-white/70 px-3 text-sm text-slate-700">
                <input
                  id="ten-dlc-campaign-direct-lending"
                  type="checkbox"
                  bind:checked={form.directLending.value}
                  disabled={loading}
                  class="accent-sky-600 size-4"
                />
                Campaign concerns direct lending
              </label>
            </div>
            <label
              class="mt-4 flex items-start gap-3 rounded-xl border border-sky-200 bg-sky-50/70 p-3 text-sm text-slate-700"
            >
              <input
                id="ten-dlc-campaign-terms"
                type="checkbox"
                bind:checked={form.termsAndConditions.value}
                disabled={loading}
                class="accent-sky-600 mt-0.5 size-4"
              />
              <span>I confirm that subscribers opt in, can request help, and can opt out at any time.</span>
            </label>
            <FieldError class="mt-2" error={form.termsAndConditions.error} />
          </section>

          <FieldError class="mt-4" error={form.error} />
          <div class="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
            <Button class="w-full sm:w-auto" variant="secondary" onclick={() => window.history.back()}>Cancel</Button>
            <Button
              id="ten-dlc-campaign-submit"
              class="w-full sm:w-auto"
              submit
              spinner={form.loading}
              disabled={loading || form.loading}>Submit campaign</Button
            >
          </div>
        </form>
      {/if}
    </Card>
  </div>
</div>

// src/routes/(app)/phone/10dlc/campaign/(form)/(routes)/add/+page.tsx
import { useNavigate } from "@solidjs/router";
import { createSignal, For, onSettled, Show } from "solid-js";
import { createStore } from "~/lib/state/store";
import {
  CreateTenDlcCampaignDocument,
  TenDlcCampaignBrandDocument,
  TenDlcCampaignDocumentUploadUrlDocument,
  type TenDlcCampaignInput,
  type TenDlcCampaignBrandQuery,
} from "~/gql/graphql";
import { PATH_TEN_DLC } from "~/lib/app/paths";
import { Alert, Button, Card, Field, FieldError, FieldLabel, Input, PageTitle, TextArea } from "~/components";
import { tenDlcStatusLabel } from "~/lib/feature/phone/phone-display";
import { graphqlClient } from "~/lib/graphql/client";
import { showInfo } from "~/lib/state/notifications";
type Brand = TenDlcCampaignBrandQuery["tenDlcBrand"];
interface FormState {
  ageGated: boolean;
  description: string;
  directLending: boolean;
  documentUrl: string;
  embeddedLink: boolean;
  embeddedPhone: boolean;
  helpKeywords: string;
  helpMessage: string;
  messageFlow: string;
  numberPool: boolean;
  optInKeywords: string;
  optOutKeywords: string;
  optoutMessage: string;
  sampleMessage1: string;
  sampleMessage2: string;
  termsAndConditions: boolean;
  usecase: string;
}
const usecases = [
  "MIXED",
  "CUSTOMER_CARE",
  "DELIVERY_NOTIFICATION",
  "ACCOUNT_NOTIFICATION",
  "2FA",
  "MARKETING",
  "LOW_VOLUME_MIXED",
  "PUBLIC_SERVICE_ANNOUNCEMENT",
  "SECURITY_ALERT",
  "SOLE_PROPRIETOR",
];
export default function TenDlcCampaignAddPage() {
  const navigate = useNavigate();
  const [brand, setBrand] = createSignal<Brand | null>(null);
  const [loading, setLoading] = createSignal(true);
  const [saving, setSaving] = createSignal(false);
  const [uploading, setUploading] = createSignal(false);
  const [error, setError] = createSignal<string | null>(null);
  const [errors, setErrors] = createSignal<Record<string, string>>({});
  const [form, setForm] = createStore<FormState>({
    ageGated: false,
    description: "",
    directLending: false,
    documentUrl: "",
    embeddedLink: false,
    embeddedPhone: false,
    helpKeywords: "HELP, INFO",
    helpMessage: "Reply HELP for help. Message and data rates may apply.",
    messageFlow: "",
    numberPool: false,
    optInKeywords: "START, YES",
    optOutKeywords: "STOP, END, CANCEL, UNSUBSCRIBE",
    optoutMessage: "You have opted out and will receive no further messages. Reply START to opt back in.",
    sampleMessage1: "",
    sampleMessage2: "",
    termsAndConditions: false,
    usecase: "MIXED",
  });
  onSettled(() => void loadBrand());
  async function loadBrand(): Promise<void> {
    setLoading(true);
    try {
      const response = await graphqlClient.query(TenDlcCampaignBrandDocument, {}, { requestPolicy: "network-only" });
      if (response.error || !response.data?.tenDlcBrand) throw new Error();
      setBrand(response.data.tenDlcBrand);
    } catch {
      setError("Register a 10DLC brand before adding a campaign.");
    } finally {
      setLoading(false);
    }
  }
  async function uploadDocument(file: File): Promise<void> {
    setUploading(true);
    setError(null);
    try {
      const response = await graphqlClient.query(
        TenDlcCampaignDocumentUploadUrlDocument,
        { filename: file.name },
        { requestPolicy: "network-only" },
      );
      const upload = response.data?.campaignMediaUploadUrl;
      if (response.error || !upload) throw new Error();
      const result = await fetch(upload.uploadUrl, {
        method: "PUT",
        headers: { "Content-Type": file.type || "application/octet-stream" },
        body: file,
      });
      if (!result.ok) throw new Error();
      setForm("documentUrl", upload.mediaUrl);
    } catch {
      setError("Could not upload consent document.");
    } finally {
      setUploading(false);
    }
  }
  async function submit(event: SubmitEvent): Promise<void> {
    event.preventDefault();
    const next = validate(form);
    setErrors(next);
    if (Object.keys(next).length) return;
    setSaving(true);
    setError(null);
    try {
      const input: TenDlcCampaignInput = {
        ageGated: form.ageGated,
        description: form.description.trim(),
        directLending: form.directLending,
        embeddedLink: form.embeddedLink,
        embeddedPhone: form.embeddedPhone,
        helpKeywords: split(form.helpKeywords),
        helpMessage: form.helpMessage.trim(),
        messageFlow: `${form.messageFlow.trim()}\nConsent documentation: ${form.documentUrl}`,
        numberPool: form.numberPool,
        optInKeywords: split(form.optInKeywords),
        optOutKeywords: split(form.optOutKeywords),
        optoutMessage: form.optoutMessage.trim(),
        sampleMessages: [form.sampleMessage1.trim(), form.sampleMessage2.trim()],
        subscriberHelp: true,
        subscriberOptIn: true,
        subscriberOptOut: true,
        termsAndConditions: true,
        usecase: form.usecase,
      };
      const response = await graphqlClient.mutation(CreateTenDlcCampaignDocument, { input });
      if (response.error || !response.data?.createTenDlcCampaign) throw new Error();
      showInfo("10DLC campaign registration submitted.");
      navigate(PATH_TEN_DLC);
    } catch {
      setError("Could not submit 10DLC campaign registration.");
    } finally {
      setSaving(false);
    }
  }
  const verified = () =>
    !brand()?.providerStatus || ["VERIFIED", "VETTED_VERIFIED"].includes(brand()!.providerStatus!.toUpperCase());
  return (
    <div class="flex h-dvh min-h-0 flex-col rounded-2xl bg-gradient-to-br from-slate-100 via-slate-50 to-stone-100 p-2 sm:h-[calc(100dvh-3rem)] sm:p-3">
      <PageTitle title="Register 10DLC campaign">
        <a href={PATH_TEN_DLC} class="text-sm font-medium text-sky-700">
          10DLC
        </a>
      </PageTitle>
      <div class="flex min-h-0 grow justify-center overflow-y-auto pt-2 pb-18">
        <Card variant="panel" class="h-fit w-full max-w-4xl p-4 sm:p-6">
          <Show
            when={!error() || brand()}
            fallback={
              <Alert type="warning" layout="inline">
                {error()}
              </Alert>
            }
          >
            <Show
              when={loading() || verified()}
              fallback={
                <Alert type="warning" layout="inline">
                  {brand()?.name} is {tenDlcStatusLabel(brand()?.providerStatus).toLowerCase()}. Registration is
                  available after verification.
                </Alert>
              }
            >
              <form onSubmit={(event) => void submit(event)} aria-busy={loading() || saving() ? "true" : "false"}>
                <Section title="Messaging use case">
                  <div class="grid gap-4 sm:grid-cols-2">
                    <Field>
                      <FieldLabel for="ten-dlc-usecase">Use case</FieldLabel>
                      <select
                        id="ten-dlc-usecase"
                        class="glass-input h-10 w-full px-3"
                        value={form.usecase}
                        onChange={(event) => setForm("usecase", event.currentTarget.value)}
                      >
                        <For each={usecases}>
                          {(usecase) => <option value={usecase}>{usecase.replaceAll("_", " ")}</option>}
                        </For>
                      </select>
                    </Field>
                    <TextField
                      area
                      field="description"
                      label="Description"
                      form={form}
                      setForm={setForm}
                      errors={errors()}
                    />
                  </div>
                </Section>
                <Section title="Consent and opt-in">
                  <div class="grid gap-4 sm:grid-cols-2">
                    <TextField
                      area
                      wide
                      field="messageFlow"
                      label="How customers opt in"
                      form={form}
                      setForm={setForm}
                      errors={errors()}
                    />
                    <Field>
                      <FieldLabel for="consent-document">Consent document</FieldLabel>
                      <input
                        id="consent-document"
                        type="file"
                        disabled={uploading()}
                        onChange={(event) => {
                          const file = event.currentTarget.files?.[0];
                          if (file) void uploadDocument(file);
                        }}
                      />
                      <p class="mt-1 text-xs text-slate-500">
                        {form.documentUrl ? "Uploaded" : uploading() ? "Uploading…" : "Required"}
                      </p>
                      <FieldError error={errors().documentUrl} />
                    </Field>
                    <TextField
                      field="optInKeywords"
                      label="Opt-in keywords"
                      form={form}
                      setForm={setForm}
                      errors={errors()}
                    />
                  </div>
                </Section>
                <Section title="Message samples">
                  <div class="grid gap-4 sm:grid-cols-2">
                    <TextField
                      area
                      field="sampleMessage1"
                      label="Sample message 1"
                      form={form}
                      setForm={setForm}
                      errors={errors()}
                    />
                    <TextField
                      area
                      field="sampleMessage2"
                      label="Sample message 2"
                      form={form}
                      setForm={setForm}
                      errors={errors()}
                    />
                  </div>
                </Section>
                <Section title="Help and opt-out">
                  <div class="grid gap-4 sm:grid-cols-2">
                    <TextField
                      field="helpKeywords"
                      label="Help keywords"
                      form={form}
                      setForm={setForm}
                      errors={errors()}
                    />
                    <TextField
                      field="optOutKeywords"
                      label="Opt-out keywords"
                      form={form}
                      setForm={setForm}
                      errors={errors()}
                    />
                    <TextField
                      area
                      field="helpMessage"
                      label="Help response"
                      form={form}
                      setForm={setForm}
                      errors={errors()}
                    />
                    <TextField
                      area
                      field="optoutMessage"
                      label="Opt-out response"
                      form={form}
                      setForm={setForm}
                      errors={errors()}
                    />
                  </div>
                </Section>
                <Section title="Content declarations">
                  <div class="grid gap-2 sm:grid-cols-2">
                    <For
                      each={
                        [
                          ["embeddedLink", "Messages include links"],
                          ["embeddedPhone", "Messages include phone numbers"],
                          ["numberPool", "Campaign uses a number pool"],
                          ["ageGated", "Content is age-gated"],
                          ["directLending", "Campaign concerns direct lending"],
                        ] as Array<[keyof FormState, string]>
                      }
                    >
                      {([field, label]) => (
                        <label class="flex items-center gap-3 rounded-xl bg-white/70 p-3 text-sm">
                          <input
                            type="checkbox"
                            checked={Boolean(form[field])}
                            onChange={(event) => setForm(field, event.currentTarget.checked as never)}
                          />
                          {label}
                        </label>
                      )}
                    </For>
                  </div>
                  <label class="mt-4 flex items-start gap-3 rounded-xl border border-sky-200 bg-sky-50 p-3 text-sm">
                    <input
                      type="checkbox"
                      checked={form.termsAndConditions}
                      onChange={(event) => setForm("termsAndConditions", event.currentTarget.checked)}
                    />
                    I confirm subscribers opt in, can request help, and can opt out.
                  </label>
                  <FieldError error={errors().termsAndConditions} />
                </Section>
                <FieldError class="mt-4" error={error()} />
                <div class="mt-6 flex justify-end gap-2">
                  <Button variant="secondary" onClick={() => navigate(PATH_TEN_DLC)}>
                    Cancel
                  </Button>
                  <Button submit spinner={saving()} disabled={loading() || uploading()}>
                    Submit campaign
                  </Button>
                </div>
              </form>
            </Show>
          </Show>
        </Card>
      </div>
    </div>
  );
}
function Section(props: { children: unknown; title: string }) {
  return (
    <section class="border-b border-slate-200/80 py-5 first:pt-0">
      <h2 class="text-lg font-semibold">{props.title}</h2>
      <div class="mt-4">{props.children as never}</div>
    </section>
  );
}
function TextField(props: {
  area?: boolean;
  errors: Record<string, string>;
  field: keyof FormState;
  form: FormState;
  label: string;
  setForm: ReturnType<typeof createStore<FormState>>[1];
  wide?: boolean;
}) {
  return (
    <Field class={props.wide ? "sm:col-span-2" : undefined}>
      <FieldLabel for={`ten-dlc-${props.field}`}>{props.label}</FieldLabel>
      <Show
        when={props.area}
        fallback={
          <Input
            id={`ten-dlc-${props.field}`}
            value={String(props.form[props.field])}
            error={props.errors[props.field]}
            onInput={(event) => props.setForm(props.field, event.currentTarget.value as never)}
          />
        }
      >
        <TextArea
          id={`ten-dlc-${props.field}`}
          rows={4}
          value={String(props.form[props.field])}
          error={props.errors[props.field]}
          onInput={(event) => props.setForm(props.field, event.currentTarget.value as never)}
        />
      </Show>
      <FieldError error={props.errors[props.field]} />
    </Field>
  );
}
function validate(form: FormState): Record<string, string> {
  const errors: Record<string, string> = {};
  for (const field of [
    "description",
    "documentUrl",
    "helpKeywords",
    "helpMessage",
    "messageFlow",
    "optOutKeywords",
    "optoutMessage",
    "sampleMessage1",
    "sampleMessage2",
  ] as const)
    if (!form[field].trim()) errors[field] = "Required";
  if (!form.termsAndConditions) errors.termsAndConditions = "Accept the terms and conditions";
  return errors;
}
function split(value: string): string[] {
  return value
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
}
